try:
	from . import buildings
except ImportError:
	import buildings
Droppers = []
Upgraders = []
Processors = []

Droppers.append(buildings.Dropper(name="Basic Dropper", eff=1))
Droppers.append(buildings.Dropper(name="Advanced Dropper", eff=2))
Droppers.append(buildings.Dropper(name="Poisoned Dripper", eff=3, bonus={"Acid": 2}, vulnerabilities=["Wet"]))
Droppers.append(buildings.Dropper(name="Coal Drill", eff=5, immunities=["Fire"]))
Droppers.append(buildings.Dropper(name="Electric Dropper", eff=10, vulnerabilities=["Wet"]))
Droppers.append(buildings.Dropper(name="Ancient Ruins", eff=16, bonus={"Ancient": 1.2}, immunities=["Acid"]))
Droppers.append(buildings.Dropper(name="Slime Duper", eff=20, bonus={"Slimed": 1.3}))
Droppers.append(buildings.Dropper(name="Flower Forest", eff=25, bonus={"Nebula": 0.9, "Ice": 0.1}, vulnerabilities=["Fire"]))
Droppers.append(buildings.Dropper(name="Sea Dropper", eff=37, bonus={"Wet": 1.5}, immunities=["Fire"]))
Droppers.append(buildings.Dropper(name="Ice Dropper", eff=41, vulnerabilities=["Fire"]))
Droppers.append(buildings.Dropper(name="Dupe Error", eff=75, bonus={"Nuclear": 1.5}, vulnerabilities=["Acid"]))
Droppers.append(buildings.Dropper(name="Timmy the Tree", eff=100, bonus={"Aired": 1.2}))
Droppers.append(buildings.Dropper(name="Shard Harvester", eff=119, bonus={"Nebula": 1.3}, immunities=["Nuclear"]))
Droppers.append(buildings.Dropper(name="Steampunk Terminator", eff=132, bonus={"Fueled": 1.7}, vulnerabilities=["Acid"]))
Droppers.append(buildings.Dropper(name="Magical Tree", eff=150, bonus={"Aired": 1.45}, immunities=["Nuclear"]))
Droppers.append(buildings.Dropper(name="Aegis", eff=183.3333333, bonus={"Nebula": 2}, immunities=["Nuclear"]))

Upgraders.append(buildings.Upgrader(name="Copper Upgrader", mult=1.5))
Upgraders.append(buildings.Upgrader(name="Ore Scanner", mult=2, bonuses={"Aired": 1.5}))
Upgraders.append(buildings.Upgrader(name="Fire Laser", mult=2.5, effect_remove=["Wet"], trans_effect={"Wet": "Fire"}))
Upgraders.append(buildings.Upgrader(name="Blue Simulation", mult=7, effect_add=["Wet"]))
Upgraders.append(buildings.Upgrader(name="Coral Sea", mult=10, effect_add=["Wet", "Wet"], effect_remove=["Fire"]))
Upgraders.append(buildings.Upgrader(name="Ice Wind", mult=12, effect_add=["Ice"]))
Upgraders.append(buildings.Upgrader(name="Nuclear Waste", mult=13, effect_add=["Nuclear"], destroy_chance=0.2))
Upgraders.append(buildings.Upgrader(name="Surge Light", mult=15, bonuses={"Aired": 1.3}))
Upgraders.append(buildings.Upgrader(name="Mystical Swamp", mult=17, effect_add=["Slimed"], bonuses={"Slimed": 1.3}, destroy_chance=0.01))
Upgraders.append(buildings.Upgrader(name="Magnetic Fuser", mult=18, effect_add=["Magnetic", "Nuclear"], cond_effect_add={"Nuclear": "Nebula"}))
Upgraders.append(buildings.Upgrader(name="Sandy Valley", mult=21, effect_add=["Ancient"]))
Upgraders.append(buildings.Upgrader(name="Water Mountain", mult=25, effect_add=["Wet"], effect_remove=["Fire"], destroy_chance=0.05))
Upgraders.append(buildings.Upgrader(name="Acid Leak", mult=31, effect_add=["Acid"]))
Upgraders.append(buildings.Upgrader(name="Northern Lights", mult=33, effect_add=["Aired", "Ice"], effect_remove=["Fire"], bonuses={"Nuclear": 0.5}))
Upgraders.append(buildings.Upgrader(name="Temple of Silence", mult=25, effect_remove=["All"]))
Upgraders.append(buildings.Upgrader(name="Death Waste", mult=35, effect_add=["V-Wet"], bonuses={"Nuclear": 2}))
Upgraders.append(buildings.Upgrader(name="Sunstone", mult=37, effect_add=["Fire", "Fire", "Fire", "Fire", "Fire"]))
Upgraders.append(buildings.Upgrader(name="Nuclear Lab", mult=43, trans_effect={"Acid": "Nuclear"}, bonuses={"Nuclear": 1.5}))
Upgraders.append(buildings.Upgrader(name="Amethyst Singularity", mult=50, bonuses={"Nebula": 2}))
Upgraders.append(buildings.Upgrader(name="Creations Studio", mult=55, effect_add=["Ice", "Magnetic", "Aired"]))
Upgraders.append(buildings.Upgrader(name="Spring Sunshine", mult=60, effect_remove=["Wet", "Nuclear"]))
Upgraders.append(buildings.Upgrader(name="Storming Summit", mult=64, effect_add=["Magnetic"], effect_remove=["Acid"], bonuses={"Magnetic": 1.2}, destroy_chance=0.25))
Upgraders.append(buildings.Upgrader(name="Shinigami Realm", mult=72, bonuses={"Ancient": 1.6}))
Upgraders.append(buildings.Upgrader(name="Aegis Upgrader", mult=89, effect_add=["Nebula"], bonuses={"Nuclear": 2}))
Upgraders.append(buildings.Upgrader(name="Infernal Realm", mult=99, effect_add=["Fire", "Fire", "Fire"], effect_remove=["Wet"], bonuses={"Fire": 1.66}))
Upgraders.append(buildings.Upgrader(name="Ancient Gate", mult=120, effect_add=["Fire"], bonuses={"Ancient": 1.3}))

Processors.append(buildings.Processor(name="Copper Processor", mult=1.5))
Processors.append(buildings.Processor(name="Cardboard Boxes", mult=2, refuse=["Acid"]))
Processors.append(buildings.Processor(name="Golden Forge", mult=3, bonus={"Fire": 1.5}))
Processors.append(buildings.Processor(name="Magnet Staff", mult=5, bonus={"Magnetic": 1.5}))
Processors.append(buildings.Processor(name="Space Processor", mult=12, bonus={"Nebula": 1.5}, onlyaccept=["Nebula"]))
Processors.append(buildings.Processor(name="Mushroom Spores", mult=22, bonus={"Acid": 2.5}, onlyaccept=["Acid"]))
Processors.append(buildings.Processor(name="Vortex Shrine", mult=25, bonus={"Nuclear": 2.5},))
Processors.append(buildings.Processor(name="Subzero", mult=27, bonus={"Wet": 2}, refuse=["Fire"]))
Processors.append(buildings.Processor(name="Flying Isles", mult=41, bonus={"Aired": 2.5}))
Processors.append(buildings.Processor(name="Portal of Blocks", mult=63, bonus={"Fire": 2}, refuse=["Wet"]))
Processors.append(buildings.Processor(name="Hand of Ancient", mult=91, bonus={"Ancient": 1.5}, refuse=["Fire"]))